# Generated by Django 5.1.5 on 2025-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_py_question_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='py_question',
            name='level',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='py_question',
            name='type',
            field=models.CharField(default='python', max_length=20),
        ),
    ]
