# Generated by Django 5.1.5 on 2025-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_py_question_level_py_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='py_question',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='py_question',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
